package Kasir;

import KoneksiDB.KoneksiDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.sql.Date;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;

public class Kasir extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    private PreparedStatement stat;
    private ResultSet rs;
    KoneksiDB KoneksiDB = new KoneksiDB();

    public Kasir() {
        initComponents();
        AturKolom();
        AturBaris();
        id_auto();
    }

    public void AturKolom() {
        dtm.addColumn("No Transaksi");
        dtm.addColumn("Nama Customer");
        dtm.addColumn("No Telepon");
        dtm.addColumn("Kode Pesanan");
        dtm.addColumn("Nama Pesanan");
        dtm.addColumn("Total Pesanan");
        dtm.addColumn("Harga Satuan");
        dtm.addColumn("Total Harga");
        dtm.addColumn("Note");
        dtm.addColumn("Tanggal Penerimaan");
        dtm.addColumn("Jumlah Harga");
        jTable1.setModel(dtm);
    }

    public void AturBaris() {
        dtm.setRowCount(0);
        jTable1.setModel(dtm);
        ResultSet rs = KoneksiDB.ambilData("SELECT * FROM kasir");
        try {
            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getString("No_Transaksi"), rs.getString("Nama_Customer"), rs.getString("No_Telepon"),
                    rs.getString("Kode_Pesanan"), rs.getString("Nama_Pesanan"), rs.getString("Total_Pesanan"), rs.getString("Harga_Satuan"),
                    rs.getString("Total_Harga"), rs.getString("Note"), rs.getString("Tanggal_Penerimaan"), rs.getString("Jumlah_Harga")});
            }
            jTable1.setModel(dtm);
        } catch (Exception e) {
        }
    }

    public void id_auto() {
        ResultSet rs = KoneksiDB.ambilData("SELECT * FROM kasir ORDER BY No_Transaksi DESC");
        try {
            if (rs.next()) {
                String id = rs.getString("No_Transaksi");
                int idNum;
                if (id != null && !id.isEmpty()) {
                    try {
                        idNum = Integer.parseInt(id.replaceAll("[^0-9]", ""));
                        idNum++;
                    } catch (NumberFormatException e) {
                        // Handle the case where the No_Transaksi field is not in the expected format
                        idNum = 1;
                    }
                } else {
                    // Handle the case where the No_Transaksi field is empty
                    idNum = 1;
                }
                String result = String.valueOf(idNum);
                jNoTransaksi.setText(result);
            } else {
                // Handle the case where the result set is empty
                jNoTransaksi.setText("1");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String UbahFormatJCalendar(java.sql.Date abc) {
        SimpleDateFormat dtFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            return dtFormat.format(abc);
        } catch (Exception e) {
            System.err.println("Error:" + e.getMessage());
            return " ";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jNamaCustomer = new javax.swing.JTextField();
        jNoTransaksi = new javax.swing.JTextField();
        jNoTelepon = new javax.swing.JTextField();
        jNamaPesanan = new javax.swing.JTextField();
        jTotalPesanan = new javax.swing.JTextField();
        jHargaSatuan = new javax.swing.JTextField();
        jKodePesanan = new javax.swing.JComboBox<>();
        jTambahData = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTotalHarga = new javax.swing.JTextField();
        jNote = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelKasir = new javax.swing.JLabel();
        jLabelDaftarPesanan = new javax.swing.JLabel();
        jLabelRiwayatPesanan = new javax.swing.JLabel();
        jLabelDataProduk = new javax.swing.JLabel();
        jLabelLaporanPenjualan = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jJumlahHarga = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jCalendar = new com.toedter.calendar.JDateChooser();
        jHitungData = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Nama Customer", "No Telepon", "Kode Pesanan ", "Nama Pesanan", "Total Pesanan", "Harga Satuan", "Total Harga", "Tanggal Penerimaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 1330, 190));

        jPanel2.setBackground(new java.awt.Color(80, 114, 123));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 70));

        jButton1.setBackground(new java.awt.Color(80, 114, 123));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("TAMBAH DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 540, -1, -1));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 520, 60, 50));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel1.setText("No. Transaksi");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel7.setText("Harga Satuan");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel2.setText("Nama Customer");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel3.setText("No. Telepon");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel4.setText("Kode Pesanan");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel5.setText("Nama Pesanan");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel6.setText("Total Pesanan");

        jNamaCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNamaCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaCustomerActionPerformed(evt);
            }
        });

        jNoTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNoTransaksi.setEnabled(false);
        jNoTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoTransaksiActionPerformed(evt);
            }
        });

        jNoTelepon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoTeleponActionPerformed(evt);
            }
        });

        jNamaPesanan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNamaPesanan.setEnabled(false);
        jNamaPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaPesananActionPerformed(evt);
            }
        });

        jTotalPesanan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTotalPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalPesananActionPerformed(evt);
            }
        });

        jHargaSatuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jHargaSatuan.setEnabled(false);
        jHargaSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHargaSatuanActionPerformed(evt);
            }
        });

        jKodePesanan.setSelectedItem(jKodePesanan);
        jKodePesanan.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jKodePesananPopupMenuWillBecomeVisible(evt);
            }
        });
        jKodePesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKodePesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNamaCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jNoTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jNamaPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jTotalPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jHargaSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jNoTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jKodePesanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNoTransaksi))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNamaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jKodePesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jNamaPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTotalPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 590, 360));

        jTambahData.setBackground(new java.awt.Color(80, 114, 123));
        jTambahData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTambahData.setForeground(new java.awt.Color(204, 204, 204));
        jTambahData.setText("TAMBAH");
        jTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTambahDataActionPerformed(evt);
            }
        });
        jPanel1.add(jTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 410, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel8.setText("Total Harga");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel9.setText("Note");

        jTotalHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalHargaActionPerformed(evt);
            }
        });

        jNote.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNote, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jNote, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 570, 260));

        jPanel3.setBackground(new java.awt.Color(80, 114, 123));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 700));

        jLabelKasir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelKasir.setForeground(new java.awt.Color(204, 204, 204));
        jLabelKasir.setText("KASIR");
        jLabelKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKasirMouseClicked(evt);
            }
        });

        jLabelDaftarPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDaftarPesanan.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDaftarPesanan.setText("DAFTAR PESANAN");
        jLabelDaftarPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDaftarPesananMouseClicked(evt);
            }
        });

        jLabelRiwayatPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelRiwayatPesanan.setForeground(new java.awt.Color(204, 204, 204));
        jLabelRiwayatPesanan.setText("RIWAYAT PESANAN");
        jLabelRiwayatPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRiwayatPesananMouseClicked(evt);
            }
        });

        jLabelDataProduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDataProduk.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDataProduk.setText("DATA PRODUK");
        jLabelDataProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDataProdukMouseClicked(evt);
            }
        });

        jLabelLaporanPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLaporanPenjualan.setForeground(new java.awt.Color(204, 204, 204));
        jLabelLaporanPenjualan.setText("LAPORAN PENJUALAN");
        jLabelLaporanPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLaporanPenjualanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDataProduk)
                            .addComponent(jLabelRiwayatPesanan))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDaftarPesanan)
                            .addComponent(jLabelKasir)
                            .addComponent(jLabelLaporanPenjualan))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabelKasir)
                .addGap(50, 50, 50)
                .addComponent(jLabelDaftarPesanan)
                .addGap(49, 49, 49)
                .addComponent(jLabelRiwayatPesanan)
                .addGap(54, 54, 54)
                .addComponent(jLabelDataProduk)
                .addGap(42, 42, 42)
                .addComponent(jLabelLaporanPenjualan)
                .addContainerGap(764, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 1140));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel10.setText("Jumlah Harga");
        jLabel10.setMaximumSize(new java.awt.Dimension(113, 23));
        jLabel10.setMinimumSize(new java.awt.Dimension(113, 23));
        jLabel10.setPreferredSize(new java.awt.Dimension(113, 23));

        jJumlahHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jJumlahHarga.setEnabled(false);
        jJumlahHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJumlahHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 370, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel12.setText("Tanggal Penerimaan");
        jLabel12.setMaximumSize(new java.awt.Dimension(113, 23));
        jLabel12.setMinimumSize(new java.awt.Dimension(113, 23));
        jLabel12.setPreferredSize(new java.awt.Dimension(113, 23));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, 460, 60));

        jHitungData.setBackground(new java.awt.Color(80, 114, 123));
        jHitungData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jHitungData.setForeground(new java.awt.Color(204, 204, 204));
        jHitungData.setText("HITUNG");
        jHitungData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHitungDataActionPerformed(evt);
            }
        });
        jPanel1.add(jHitungData, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 90, -1));

        jHapus.setBackground(new java.awt.Color(80, 114, 123));
        jHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jHapus.setForeground(new java.awt.Color(204, 204, 204));
        jHapus.setText("HAPUS");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });
        jPanel1.add(jHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 90, -1));

        jButton9.setBackground(new java.awt.Color(80, 114, 123));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 204, 204));
        jButton9.setText("SELESAI");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 540, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2118, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jJumlahHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJumlahHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJumlahHargaActionPerformed

    private void jHargaSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHargaSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHargaSatuanActionPerformed

    private void jTotalPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalPesananActionPerformed

    private void jNamaPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaPesananActionPerformed

    private void jNoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNoTeleponActionPerformed

    private void jNoTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNoTransaksiActionPerformed

    private void jNamaCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaCustomerActionPerformed

    private void jTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalHargaActionPerformed

    private void jNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNoteActionPerformed

    private void jTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahDataActionPerformed
        String No_Transaksi = jNoTransaksi.getText();
        String Nama_Customer = jNamaCustomer.getText();
        String No_Telepon = jNoTelepon.getText();
        String Kode_Pesanan = jKodePesanan.getSelectedItem().toString();
        String Nama_Pesanan = jNamaPesanan.getText();
        String Total_Pesanan = jTotalPesanan.getText();
        String Harga_Satuan = jHargaSatuan.getText();
        String Jumlah_Harga = jJumlahHarga.getText();
        String Total_Harga = jTotalHarga.getText();
        String Note = jNote.getText();
        java.sql.Date Tanggal_Penerimaan = new java.sql.Date(jCalendar.getDate().getTime());

        if (jNamaCustomer.getText().length() <= 0
                || jNoTelepon.getText().length() <= 0
                || jKodePesanan.getSelectedItem() == null
                || jNamaPesanan.getText().length() <= 0
                || jTotalPesanan.getText().length() <= 0
                || jHargaSatuan.getText().length() <= 0
                || jJumlahHarga.getText().length() <= 0
                || jTotalHarga.getText().length() <= 0
                || jNote.getText().length() <= 0
                || jCalendar.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Masukkan Data yang Kurang");
            id_auto();
        } else {
            KoneksiDB.aksi("INSERT INTO `kasir`(`No_Transaksi`, `Nama_Customer`, `No_Telepon`, `Kode_Pesanan`, `Nama_Pesanan`, `Total_Pesanan`, `Harga_Satuan`, `Total_Harga`, `Note`, `Tanggal_Penerimaan`, `Jumlah_Harga`) VALUES ('" + No_Transaksi + "','" + Nama_Customer + "','" + No_Telepon + "','" + Kode_Pesanan + "','" + Nama_Pesanan + "','" + Total_Pesanan + "','" + Harga_Satuan + "','" + Total_Harga + "','" + Note + "','" + Tanggal_Penerimaan + "','" + Jumlah_Harga + "')");

            jNoTransaksi.setText("");
            jNamaCustomer.setText("");
            jNoTelepon.setText("");
            jKodePesanan.setSelectedItem("");
            jNamaPesanan.setText("");
            jTotalPesanan.setText("");
            jHargaSatuan.setText("");
            jTotalHarga.setText("");
            jJumlahHarga.setText("");
            jNote.setText("");
            jCalendar.setDate(null);
            AturBaris();

            id_auto();
            JOptionPane.showMessageDialog(null, "Data Ditambahkan");
        }
    }//GEN-LAST:event_jTambahDataActionPerformed

    private void jHitungDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHitungDataActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jHargaSatuan.getText())
                && !"".equals(jTotalPesanan.getText())) {
            int harga = Integer.parseInt(jHargaSatuan.getText());
            int jumlah = Integer.parseInt(jTotalPesanan.getText());
            int subTotal = harga * jumlah;
            jTotalHarga.setText(Integer.toString(subTotal));
            jJumlahHarga.setText(Integer.toString(subTotal));
        } else {
            JOptionPane.showMessageDialog(null, "Anda harus mengisi data dengan lengkap", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jHitungDataActionPerformed

    private void jLabelKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKasirMouseClicked
//        Kasir c = new Kasir();
//        this.hide();
//        c.setVisible(true);
    }//GEN-LAST:event_jLabelKasirMouseClicked

    private void jLabelDaftarPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDaftarPesananMouseClicked
//        DaftarPesanan c = new DaftarPesanan();
//        this.hide();
//        c.setVisible(true);
    }//GEN-LAST:event_jLabelDaftarPesananMouseClicked

    private void jLabelRiwayatPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRiwayatPesananMouseClicked
//        RiwayatPesanan c = new RiwayatPesanan();
//        this.hide();
//        c.setVisible(true);
    }//GEN-LAST:event_jLabelRiwayatPesananMouseClicked

    private void jLabelDataProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDataProdukMouseClicked
//        DataProduk c = new DataProduk();
//        this.hide();
//        c.setVisible(true);
    }//GEN-LAST:event_jLabelDataProdukMouseClicked

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        // TODO add your handling code here:
        jHapus.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                jNamaCustomer.setText("");
                jNoTelepon.setText("");
                jKodePesanan.setSelectedItem("");
                jNamaPesanan.setText("");
                jTotalPesanan.setText("");
                jHargaSatuan.setText("");
                jTotalHarga.setText("");
                jJumlahHarga.setText("");
                jNote.setText("");
                jCalendar.setDate(null);
            }
        });
    }//GEN-LAST:event_jHapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelLaporanPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLaporanPenjualanMouseClicked
//        LaporanPenjualan c = new LaporanPenjualan();
//        this.hide();
//        c.setVisible(true);
    }//GEN-LAST:event_jLabelLaporanPenjualanMouseClicked

    private void jKodePesananPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jKodePesananPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        String query = "SELECT Kode_Pesanan FROM data_produk ORDER BY Kode_Pesanan ASC";
        try (PreparedStatement statement = KoneksiDB.con.prepareStatement(query)) {
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                String kodePesanan = resultSet.getString("Kode_Pesanan");
                comboBoxModel.addElement(kodePesanan);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        jKodePesanan.setModel(comboBoxModel);
        jKodePesanan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedKodePesanan = (String) jKodePesanan.getSelectedItem();

                String query = "SELECT Nama_Pesanan, Harga_Satuan FROM data_produk WHERE Kode_Pesanan = ?";
                try (PreparedStatement statement = KoneksiDB.con.prepareStatement(query)) {
                    statement.setString(1, selectedKodePesanan);
                    ResultSet resultSet = statement.executeQuery();

                    if (resultSet.next()) {
                        String namaPesanan = resultSet.getString("Nama_Pesanan");
                        String hargaSatuan = resultSet.getString("Harga_Satuan");
                        jNamaPesanan.setText(namaPesanan);
                        jHargaSatuan.setText(hargaSatuan);
                    } else {
                        jNamaPesanan.setText("");
                        jHargaSatuan.setText("");
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }//GEN-LAST:event_jKodePesananPopupMenuWillBecomeVisible

    private void jKodePesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKodePesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKodePesananActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jCalendar;
    private javax.swing.JButton jHapus;
    private javax.swing.JTextField jHargaSatuan;
    private javax.swing.JButton jHitungData;
    private javax.swing.JTextField jJumlahHarga;
    private javax.swing.JComboBox<String> jKodePesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDaftarPesanan;
    private javax.swing.JLabel jLabelDataProduk;
    private javax.swing.JLabel jLabelKasir;
    private javax.swing.JLabel jLabelLaporanPenjualan;
    private javax.swing.JLabel jLabelRiwayatPesanan;
    private javax.swing.JTextField jNamaCustomer;
    private javax.swing.JTextField jNamaPesanan;
    private javax.swing.JTextField jNoTelepon;
    private javax.swing.JTextField jNoTransaksi;
    private javax.swing.JTextField jNote;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jTambahData;
    private javax.swing.JTextField jTotalHarga;
    private javax.swing.JTextField jTotalPesanan;
    // End of variables declaration//GEN-END:variables
}
